impl StructuredReport {

    /// Compute Ic_chair_from_report.
    pub fn ic_chair_from_report(result: &AnalysisResult, report: &StructuredReport) -> Self {
        let sections = build_ic_report_sections(result, report);
        let summary = build_ic_report_summary(report);

        Self {
            report_flavor: ReportFlavor::IcChair,
            title: format!("{} / {} / IC 主席版", result.symbol, result.stock_name).into(),
            summary: summary.into(),
            recommendation: report.recommendation.clone(),
            raw_llm_recommendation: report.raw_llm_recommendation.clone(),
            recommendation_calibration_reason: report.recommendation_calibration_reason.clone(),
            confidence: report.confidence.clone(),
            raw_llm_confidence: report.raw_llm_confidence.clone(),
            confidence_score: report.confidence_score,
            confidence_breakdown: report.confidence_breakdown.clone(),
            confidence_profile: report.confidence_profile.clone(),
            confidence_caps: report.confidence_caps.clone(),
            research_reliability: report.research_reliability.clone(),
            research_confidence_score: report.research_confidence_score,
            direction_score: report.direction_score,
            direction_breakdown: report.direction_breakdown.clone(),
            action_score: report.action_score,
            action_breakdown: report.action_breakdown.clone(),
            execution_readiness: report.execution_readiness.clone(),
            execution_boundary: report.execution_boundary.clone(),
            trade_setup_quality: report.trade_setup_quality.clone(),
            calibration_summary: report.calibration_summary.clone(),
            diagnostics: report.diagnostics.clone(),
            references: report.references.clone(),
            market_chart: report.market_chart.clone(),
            user_context: report.user_context.clone(),
            price_context: report.price_context.clone(),
            probability_view: report.probability_view.clone(),
            profit_risk: report.profit_risk.clone(),
            ic_navigator: report.ic_navigator.clone(),
            ic_discipline: report.ic_discipline.clone(),
            technical_indicators: report.technical_indicators.clone(),
            evidence_cards: report.evidence_cards.clone(),
            news_insights: report.news_insights.clone(),
            risk_controls: report.risk_controls.clone(),
            action_guides: report.action_guides.clone(),
            decision_view: report.decision_view.clone(),
            core_research_call: report.core_research_call.clone(),
            mispricing_claim: report.mispricing_claim.clone(),
            why_now: report.why_now.clone(),
            required_confirmation: report.required_confirmation.clone(),
            max_initial_risk_budget: report.max_initial_risk_budget.clone(),
            appendix_reliability_summary: report.appendix_reliability_summary.clone(),
            risk_assessment: report.risk_assessment.clone(),
            rationale: report.rationale.clone(),
            research_plan: report.research_plan.clone(),
            trader_plan: report.trader_plan.clone(),
            portfolio_decision: report.portfolio_decision.clone(),
            reflection: report.reflection.clone(),
            catalyst_score_card: report.catalyst_score_card.clone(),
            review_checklist: report.review_checklist.clone(),
            stage_state: report.stage_state.clone(),
            sections,
        }
    }
}
